# Generated by Django 5.1.2 on 2024-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='posiblesmatches',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
