# Generated by Django 5.1 on 2024-11-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0003_matches_no_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='no_matches',
        ),
    ]
