# Generated by Django 5.1.3 on 2024-11-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0005_matches_no_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matchdefinitivo',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
