# Generated by Django 5.1 on 2024-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('real_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('career', models.CharField(max_length=40)),
                ('interests', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
