# Generated by Django 5.1 on 2024-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
