# Generated by Django 5.1.3 on 2024-11-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_perfil_metodo_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='Usuarios.usuario'),
            preserve_default=False,
        ),
    ]
